import 'package:flutter/material.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedBuscarWidget4.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedBuscarWidget6.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedBuscarWidget8.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedMenuInferiorWidget3.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedBuscarWidget7.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedajusteswidget6/generated/GeneratedBuscarWidget9.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuInferiorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 357.0,
                child: GeneratedBuscarWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget9(),
              )
            ]),
      ),
    ));
  }
}
