import 'package:flutter/material.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedMaskGroupWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedHagalo1Widget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedIngresatusdatosWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedBienvenidodenuevoWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedOlvidstetucontraseaWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedBotonWidget2.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedMaskGroupWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 415.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 37.0,
                child: GeneratedBienvenidodenuevoWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 30.0,
                child: GeneratedIngresatusdatosWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 41.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 43.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 22.0,
                child: GeneratedOlvidstetucontraseaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 93.0,
                child: GeneratedHagalo1Widget(),
              )
            ]),
      ),
    ));
  }
}
