import 'package:flutter/material.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedcarritowidget8/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedcarritowidget8/generated/GeneratedBuscarWidget10.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedcarritowidget8/generated/GeneratedMenuInferiorWidget4.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedcarritowidget8/generated/GeneratedNotienesnadaenelcarritoanWidget.dart';

/* Frame Carrito
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarritoWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedImage3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuInferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget10(),
              ),
              Positioned(
                left: 22.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 67.0,
                child: GeneratedNotienesnadaenelcarritoanWidget(),
              )
            ]),
      ),
    ));
  }
}
