import 'package:flutter/material.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedinputwidget/generated/GeneratedIngresatucorreoWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedinputwidget/generated/GeneratedRectangle2Widget.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 60.0,
              child: GeneratedRectangle2Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 125.0,
              height: 22.0,
              child: GeneratedIngresatucorreoWidget(),
            )
          ]),
    ));
  }
}
