import 'package:flutter/material.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedVectorWidget21.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedBotonWidget1.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedMenuInferiorWidget2.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedDeslizaparacomprarWidget.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedMartilloWidget1.dart';
import 'package:flutterapp/mi_20primera_20appapp/generatedusuariowidget4/generated/GeneratedBuscarWidget2.dart';

/* Frame Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsuarioWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedImage2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuInferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedBuscarWidget2(),
              ),
              Positioned(
                left: 44.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 422.0,
                child: GeneratedMartilloWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget1(),
              ),
              Positioned(
                left: 61.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 22.0,
                child: GeneratedDeslizaparacomprarWidget(),
              ),
              Positioned(
                left: 296.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 41.0,
                child: GeneratedVectorWidget20(),
              ),
              Positioned(
                left: 346.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 41.0,
                child: GeneratedVectorWidget21(),
              ),
              Positioned(
                left: 321.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 41.0,
                child: GeneratedVectorWidget22(),
              )
            ]),
      ),
    ));
  }
}
